const sevas=[['Book Distribution','Trains · Dadar · Andheri · More locations'],['Śrīmad-Bhāgavatam Distribution','Colonies · homes · local areas'],['Youth & Temple Enrolment','Temple registration and welcoming seva'],['Temple Seva','Deity backup · cleaning · service support'],['Poster Making','Design and prepare outreach posters'],['Purchasing Seva','Purchase items needed for programmes and parikramā'],['Guest Care','Welcome and assist visiting guests'],['Bhakti-śāstrī Seva','Study-program support seva'],['Bhakti-vaibhava Seva','Study-program support seva'],['Youth Engagement','Support Gita Life youth activities'],['Saṅkīrtana Bus Party','Coordinate bus-party related service'],['Ticket Booking','Help with travel and programme tickets'],['Weekend Stay Arrangement','Support accommodation arrangements'],['Registration Seva','Assist at programme registrations'],['Gokul · Mathura · Dvārakā Cleaning','Morning cleaning service']];
export default function Home(){return <main>
<header className="topbar"><div className="brand">GITA LIFE<span>SEVA PORTAL</span></div><div className="right-brand"><div>ISKCON JUHU</div><small>International Society for Krishna Consciousness</small></div></header>
<section className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="metadata"><source src="/gita-life-hero.mp4" type="video/mp4"/></video><div className="hero-overlay"/><div className="hero-copy"><span className="eyebrow">GITA LIFE · ISKCON JUHU</span><h1>Begin your seva,<br/><em>one step at a time.</em></h1><p>Explore seva, Gita Life programmes and ways to serve the community.</p></div><div className="scroll-mark">SCROLL TO EXPLORE ↓</div></section>
<section className="editorial"><div className="section-kicker">01 · GITA LIFE</div><div><h2>Bhagavad-gītā<br/><i>Sunday Discourse</i></h2><p>Every Sunday at 5:30 PM at ISKCON Juhu. Explore the teachings of Bhagavad-gītā through practical, relatable discussions.</p><div className="meta"><strong>EVERY SUNDAY · 5:30 PM</strong><strong>ISKCON JUHU</strong></div><button>Register for Sunday Class →</button></div><aside><small>THIS SUNDAY</small><h3>Who am I beyond this body?</h3><p>This topic is designed to be changed later from the Admin Panel.</p></aside></section>
<section className="editorial seva-intro"><div className="section-kicker">02 · SEVA</div><div><h2>How would you like<br/><i>to serve today?</i></h2><p>A growing collection of seva opportunities. Choose a service and then select its location, date and time.</p></div></section>
<section className="seva-list">{sevas.map(([title,detail],i)=><article className="seva-row" key={title}><div className="index">{String(i+1).padStart(2,'0')}</div><div><h3>{title}</h3><p>{detail}</p></div><div className="go">↗</div></article>)}</section>
<section className="inspiration"><div className="section-kicker">03 · TODAY'S INSPIRATION</div><div className="verse"><div className="ref">BHAGAVAD-GĪTĀ 18.68</div><div className="sanskrit">ya idaṁ paramaṁ guhyaṁ<br/>mad-bhakteṣv abhidhāsyati</div><p>“One who explains this supreme secret to My devotees will certainly attain pure devotional service.”</p></div></section>
<section className="closing"><div><span className="eyebrow">GITA LIFE · SEVA PORTAL</span><h2>Learn.<br/><i>Serve.</i><br/>Connect.</h2></div><div className="closing-mark">ISKCON<br/>JUHU</div></section><footer><span>GITA LIFE SEVA PORTAL · ISKCON JUHU</span><span>Admin · Seva · Gita Life</span></footer></main>}
